name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Install Dependencies
        run: |
          pnpm install
          pnpm run build

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Sync the files to EC2
          rsync -avz --delete --exclude 'node_modules' --exclude '.git' ./ $EC2_USER@$EC2_HOST:/home/ec2-user/project

          # Connect to EC2 and run commands
          ssh $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ec2-user/project
            pnpm install --production
            pm2 restart app || pm2 start build/index.js --name app
          EOF
